"""Add in_circulation field to books table

Revision ID: 5429349a2b34
Revises: d6c764b96b2d
Create Date: 2025-11-09 16:28:29.870162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5429349a2b34'
down_revision = 'd6c764b96b2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('in_circulation', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'in_circulation')
    # ### end Alembic commands ###
